-- =====================================================================
-- Infra Manager：授權 ap_user 存取 V1 建立的 31 張表（SELECT／INSERT／UPDATE／DELETE）
-- 由 rd_user（表的擁有者）登入後手動執行；表由 rd_user 自己建立，授權時不需 schema 前綴。
-- 本檔不是 Flyway migration（檔名不用 V 開頭），新增表時須補授權並重跑對應行。
-- 應用程式端以 rd_user 的 schema 前綴存取，是否建立同義詞留待 DBA 審。
-- 本檔不含任何帳號密碼或連線資訊。
-- =====================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON IM_USER TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_ROLE TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_USER_ROLE_MAP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_LOGIN_TOKEN TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_FLOW TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_FLOW_STEP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APPR TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APPR_STEP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APPR_CAND_MAP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APPR_STEP_ITEM TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_SEQ TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_CATG_MAP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_CATG_OTHER TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_REASON_MAP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_SCOPE_MAP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_EQUIP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_PLAN_STEP TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_CHECK_LIST TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_EXEC TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_VER TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_APP_EVENT TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_ATTACH TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_AI_REVIEW TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_AI_REVIEW_MSG TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_TMPL TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_FORM_OPTION TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS_PARAM TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_MAIL_OUTBOX TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_ACCESS_LOG TO ap_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON IM_RACK_CACHE TO ap_user;
