-- =====================================================================
-- Infra Manager：交易回滾整合測試專用表 IM_TX_TEST（code review 2026-10-06 裁示 ③B）
-- 用途：TransactionRollbackIT（mvnw verify 才會跑）在 @Transactional 內寫兩筆後故意丟例外，
--       驗證業務層自建的交易管理器（AppTransactionConfig）確實讓 DbClient 的多句寫入一起回滾。
--       與業務表脫鉤，業務表改版不影響本測試；表內資料由測試自己清理，平時應為空。
-- 執行方式：與 V1 相同，由 rd_user（表的擁有者）登入後手動執行；本專案不使用 Flyway。
-- 2026-10-06 複審裁示 ⑥A：補共同欄位 UPDATE_DATE／UPDATE_BY（PRD 規定每張表都有）。
--   已依舊版建過表的環境改跑 V2a__tx_test_alter.sql，不要重跑本檔。
-- 本檔不含任何帳號密碼或連線資訊。
-- =====================================================================

CREATE TABLE IM_TX_TEST (
    TX_TEST_ID          NUMBER(19)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
    TEST_KEY            VARCHAR2(64)    NOT NULL,
    MEMO                VARCHAR2(200 CHAR),
    STATUS              NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATE_DATE         DATE            DEFAULT SYSDATE NOT NULL,
    CREATE_BY           VARCHAR2(30)    NOT NULL,
    UPDATE_DATE         DATE,
    UPDATE_BY           VARCHAR2(30),
    CONSTRAINT PK_IM_TX_TEST            PRIMARY KEY (TX_TEST_ID),
    CONSTRAINT CK_IM_TX_TEST_STATUS     CHECK (STATUS IN (0, 1))
);

CREATE INDEX IND_IM_TX_TEST_01 ON IM_TX_TEST (TEST_KEY);

COMMENT ON TABLE  IM_TX_TEST             IS '交易回滾整合測試專用表；只供 TransactionRollbackIT 使用，平時應為空。退場條件：改用其他方式驗證交易時刪除';
COMMENT ON COLUMN IM_TX_TEST.TX_TEST_ID  IS '流水號（identity 自動產生）';
COMMENT ON COLUMN IM_TX_TEST.TEST_KEY    IS '單次測試的隨機鍵（UUID），測試結束依此清理';
COMMENT ON COLUMN IM_TX_TEST.MEMO        IS '測試備註';
COMMENT ON COLUMN IM_TX_TEST.STATUS      IS '1 啟用／0 停用';
COMMENT ON COLUMN IM_TX_TEST.CREATE_DATE IS '建立時間（台灣當地時間）';
COMMENT ON COLUMN IM_TX_TEST.CREATE_BY   IS '建立者，測試固定填 TEST';
COMMENT ON COLUMN IM_TX_TEST.UPDATE_DATE IS '最後更新時間';
COMMENT ON COLUMN IM_TX_TEST.UPDATE_BY   IS '最後更新人員工號';

GRANT SELECT, INSERT, UPDATE, DELETE ON IM_TX_TEST TO ap_user;
